package goflag

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// GenBashCompletion generates a bash completion script and writes it to w.
// The script provides tab completion for global flags, subcommands (including
// nested ones), and per-subcommand flags. Only long-form flags (--flag) are
// surfaced in completions to reduce clutter; short forms remain usable.
func (c *CLI) GenBashCompletion(w io.Writer) {
	binName := filepath.Base(os.Args[0])

	fmt.Fprintf(w, "#!/bin/bash\n")
	fmt.Fprintf(w, "# Bash completion for %s\n", binName)
	fmt.Fprintf(w, "# Generated by goflag\n\n")

	fmt.Fprintf(w, "_%s_completion() {\n", binName)
	fmt.Fprintf(w, "    local cur prev\n")
	fmt.Fprintf(w, "    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	fmt.Fprintf(w, "    prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n\n")

	// Collect global long flags.
	var globalFlags []string
	for _, f := range c.flags {
		globalFlags = append(globalFlags, "--"+f.name)
	}

	// Collect top-level subcommand names.
	var topNames []string
	for _, cmd := range c.subcommands {
		topNames = append(topNames, cmd.name)
	}

	fmt.Fprintf(w, "    local subcommands=%q\n", strings.Join(topNames, " "))
	fmt.Fprintf(w, "    local global_flags=%q\n\n", strings.Join(globalFlags, " "))

	// Global flags that consume an argument.
	fmt.Fprintf(w, "    case \"$prev\" in\n")
	writeBashFlagCases(w, c.flags, "        ")
	fmt.Fprintf(w, "    esac\n\n")

	// Walk the COMP_WORDS array to detect the active subcommand path.
	fmt.Fprintf(w, "    # Determine the active subcommand context.\n")
	fmt.Fprintf(w, "    local cmd_context=\"\"\n")
	fmt.Fprintf(w, "    for word in \"${COMP_WORDS[@]}\"; do\n")
	fmt.Fprintf(w, "        for cmd in $subcommands; do\n")
	fmt.Fprintf(w, "            if [[ \"$word\" == \"$cmd\" ]]; then\n")
	fmt.Fprintf(w, "                cmd_context=\"$cmd\"\n")
	fmt.Fprintf(w, "                break 2\n")
	fmt.Fprintf(w, "            fi\n")
	fmt.Fprintf(w, "        done\n")
	fmt.Fprintf(w, "    done\n\n")

	fmt.Fprintf(w, "    if [[ -z \"$cmd_context\" ]]; then\n")
	fmt.Fprintf(w, "        COMPREPLY=( $(compgen -W \"$subcommands $global_flags\" -- \"$cur\") )\n")
	fmt.Fprintf(w, "        return 0\n")
	fmt.Fprintf(w, "    fi\n\n")

	// Per-subcommand completion, recursively expanding nested subcommands.
	fmt.Fprintf(w, "    case \"$cmd_context\" in\n")
	for _, cmd := range c.subcommands {
		writeBashSubCommandCase(w, cmd, "        ")
	}
	fmt.Fprintf(w, "    esac\n\n")

	fmt.Fprintf(w, "    return 0\n")
	fmt.Fprintf(w, "}\n\n")
	fmt.Fprintf(w, "complete -F _%s_completion %s\n", binName, binName)
}

// writeBashFlagCases emits case arms for flags that require a following value,
// including file/dir-aware completions.
func writeBashFlagCases(w io.Writer, flags []*Flag, indent string) {
	for _, f := range flags {
		if f.flagType == flagBool {
			continue
		}
		var forms []string
		forms = append(forms, "--"+f.name)
		if f.shortName != "" {
			forms = append(forms, "-"+f.shortName)
		}
		fmt.Fprintf(w, "%s%s)\n", indent, strings.Join(forms, "|"))
		switch f.flagType {
		case flagDirPath:
			fmt.Fprintf(w, "%s    COMPREPLY=( $(compgen -d -- \"$cur\") )\n", indent)
		case flagFilePath:
			fmt.Fprintf(w, "%s    COMPREPLY=( $(compgen -f -- \"$cur\") )\n", indent)
		}
		fmt.Fprintf(w, "%s    return 0\n", indent)
		fmt.Fprintf(w, "%s    ;;\n", indent)
	}
}

// writeBashSubCommandCase emits a case arm for cmd and its nested children.
func writeBashSubCommandCase(w io.Writer, cmd *SubCMD, indent string) {
	fmt.Fprintf(w, "%s%s)\n", indent, cmd.name)

	inner := indent + "    "

	// Nested subcommand names for this level.
	var childNames []string
	for _, child := range cmd.subcommands {
		childNames = append(childNames, child.name)
	}

	if len(childNames) > 0 {
		fmt.Fprintf(w, "%slocal nested_cmds=%q\n", inner, strings.Join(childNames, " "))
		fmt.Fprintf(w, "%slocal nested_ctx=\"\"\n", inner)
		fmt.Fprintf(w, "%sfor word in \"${COMP_WORDS[@]}\"; do\n", inner)
		fmt.Fprintf(w, "%s    for nc in $nested_cmds; do\n", inner)
		fmt.Fprintf(w, "%s        if [[ \"$word\" == \"$nc\" ]]; then nested_ctx=\"$nc\"; break 2; fi\n", inner)
		fmt.Fprintf(w, "%s    done\n", inner)
		fmt.Fprintf(w, "%sdone\n", inner)
		fmt.Fprintf(w, "%sif [[ -z \"$nested_ctx\" ]]; then\n", inner)
	}

	// Flags that need an argument at this level.
	fmt.Fprintf(w, "%scase \"$prev\" in\n", inner)
	writeBashFlagCases(w, cmd.flags, inner+"    ")
	fmt.Fprintf(w, "%sesac\n", inner)

	var subFlags []string
	for _, f := range cmd.flags {
		subFlags = append(subFlags, "--"+f.name)
	}
	allCompletions := strings.Join(append(subFlags, childNames...), " ")
	fmt.Fprintf(w, "%sCOMPREPLY=( $(compgen -W %q -- \"$cur\") )\n", inner, allCompletions)
	fmt.Fprintf(w, "%sreturn 0\n", inner)

	if len(childNames) > 0 {
		fmt.Fprintf(w, "%sfi\n", inner)
		// Recurse into nested subcommands.
		fmt.Fprintf(w, "%scase \"$nested_ctx\" in\n", inner)
		for _, child := range cmd.subcommands {
			writeBashSubCommandCase(w, child, inner+"    ")
		}
		fmt.Fprintf(w, "%sesac\n", inner)
	}

	fmt.Fprintf(w, "%s;;\n", indent)
}

// GenZshCompletion generates a zsh completion script and writes it to w.
// The script uses the _arguments / state-machine approach and supports
// arbitrarily nested subcommands.
func (c *CLI) GenZshCompletion(w io.Writer) {
	binName := filepath.Base(os.Args[0])

	fmt.Fprintf(w, "#compdef %s\n", binName)
	fmt.Fprintf(w, "# Generated by goflag\n\n")

	fmt.Fprintf(w, "_%s() {\n", binName)
	fmt.Fprintf(w, "    local -a global_opts\n")
	fmt.Fprintf(w, "    local -a subcommands\n")
	fmt.Fprintf(w, "    local context state line\n")
	fmt.Fprintf(w, "    local ret=1\n\n")

	// Global flags.
	fmt.Fprintf(w, "    global_opts=(\n")
	for _, f := range c.flags {
		writeZshFlagSpec(w, f, "        ")
	}
	fmt.Fprintf(w, "    )\n\n")

	// Top-level subcommands.
	if len(c.subcommands) > 0 {
		fmt.Fprintf(w, "    subcommands=(\n")
		for _, cmd := range c.subcommands {
			desc := strings.ReplaceAll(cmd.description, "'", "'\\''")
			fmt.Fprintf(w, "        '%s:%s'\n", cmd.name, desc)
		}
		fmt.Fprintf(w, "    )\n\n")

		fmt.Fprintf(w, "    _arguments -C \\\n")
		fmt.Fprintf(w, "        \"${global_opts[@]}\" \\\n")
		fmt.Fprintf(w, "        '1:command:((${subcommands}))' \\\n")
		fmt.Fprintf(w, "        '*::arg:->args' \\\n")
		fmt.Fprintf(w, "        && ret=0\n\n")

		fmt.Fprintf(w, "    case $state in\n")
		fmt.Fprintf(w, "        args)\n")
		fmt.Fprintf(w, "            case $line[1] in\n")
		for _, cmd := range c.subcommands {
			writeZshSubCommandCase(w, cmd, "                ")
		}
		fmt.Fprintf(w, "            esac\n")
		fmt.Fprintf(w, "            ;;\n")
		fmt.Fprintf(w, "    esac\n")
	} else {
		fmt.Fprintf(w, "    _arguments -C \\\n")
		fmt.Fprintf(w, "        \"${global_opts[@]}\" \\\n")
		fmt.Fprintf(w, "        && ret=0\n")
	}

	fmt.Fprintf(w, "    return ret\n")
	fmt.Fprintf(w, "}\n\n")
	fmt.Fprintf(w, "_%s \"$@\"\n", binName)
}

// writeZshFlagSpec emits a single zsh _arguments flag specification line.
func writeZshFlagSpec(w io.Writer, f *Flag, indent string) {
	desc := strings.ReplaceAll(f.usage, "]", "\\]")
	desc = strings.ReplaceAll(desc, "'", "'\\''")

	argSpec := ""
	switch f.flagType {
	case flagBool:
		// no argument
	case flagDirPath:
		argSpec = ":dir:_files -/"
	case flagFilePath:
		argSpec = ":file:_files"
	default:
		argSpec = ":value:"
	}

	fmt.Fprintf(w, "%s'--%s[%s]%s'\n", indent, f.name, desc, argSpec)
}

// writeZshSubCommandCase emits the zsh state-machine case arm for cmd,
// recursing into nested subcommands when present.
func writeZshSubCommandCase(w io.Writer, cmd *SubCMD, indent string) {
	fmt.Fprintf(w, "%s%s)\n", indent, cmd.name)
	inner := indent + "    "

	if len(cmd.subcommands) > 0 {
		// Emit a nested subcommand array and recurse.
		fmt.Fprintf(w, "%slocal -a nested_cmds\n", inner)
		fmt.Fprintf(w, "%snested_cmds=(\n", inner)
		for _, child := range cmd.subcommands {
			desc := strings.ReplaceAll(child.description, "'", "'\\''")
			fmt.Fprintf(w, "%s    '%s:%s'\n", inner, child.name, desc)
		}
		fmt.Fprintf(w, "%s)\n", inner)

		fmt.Fprintf(w, "%s_arguments -C \\\n", inner)
		for _, f := range cmd.flags {
			writeZshFlagSpec(w, f, inner+"    ")
			fmt.Fprintf(w, " \\\n")
		}
		fmt.Fprintf(w, "%s    '1:command:((${nested_cmds}))' \\\n", inner)
		fmt.Fprintf(w, "%s    '*::arg:->args' \\\n", inner)
		fmt.Fprintf(w, "%s    && ret=0\n", inner)

		fmt.Fprintf(w, "%scase $state in\n", inner)
		fmt.Fprintf(w, "%s    args)\n", inner)
		fmt.Fprintf(w, "%s        case $line[1] in\n", inner)
		for _, child := range cmd.subcommands {
			writeZshSubCommandCase(w, child, inner+"            ")
		}
		fmt.Fprintf(w, "%s        esac\n", inner)
		fmt.Fprintf(w, "%s        ;;\n", inner)
		fmt.Fprintf(w, "%sesac\n", inner)
	} else {
		// Leaf subcommand — emit its flags directly.
		fmt.Fprintf(w, "%s_arguments -C \\\n", inner)
		for _, f := range cmd.flags {
			writeZshFlagSpec(w, f, inner+"    ")
			fmt.Fprintf(w, " \\\n")
		}
		fmt.Fprintf(w, "%s    && ret=0\n", inner)
	}

	fmt.Fprintf(w, "%s;;\n", indent)
}

// InstallCompletion generates and installs the completion script for the named
// shell ("bash" or "zsh") to the user's home directory, and updates the
// relevant rc file if the source line is not already present.
//
// Returns an error if the shell is not supported or if any file operation fails.
func (c *CLI) InstallCompletion(shell string) error {
	binName := filepath.Base(os.Args[0])

	var generateFunc func(io.Writer)
	switch shell {
	case "bash":
		generateFunc = c.GenBashCompletion
	case "zsh":
		generateFunc = c.GenZshCompletion
	default:
		return fmt.Errorf("unsupported shell: %s (supported: bash, zsh)", shell)
	}

	return installCompletion(shell, binName, generateFunc)
}

// UninstallCompletion removes the completion script for the named shell and
// cleans up any source/fpath lines added by InstallCompletion.
//
// Returns an error if the shell is not supported or if removal fails.
func (c *CLI) UninstallCompletion(shell string) error {
	binName := filepath.Base(os.Args[0])
	return uninstallCompletion(shell, binName)
}

// installCompletion writes the generated script to the appropriate path and
// updates the user's rc file.
func installCompletion(shell, binName string, generateFunc func(io.Writer)) error {
	var scriptContent strings.Builder
	generateFunc(&scriptContent)

	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	var installPath string

	switch shell {
	case "bash":
		completionDir := filepath.Join(homeDir, ".bash_completion.d")
		if err := os.MkdirAll(completionDir, 0755); err != nil {
			return fmt.Errorf("failed to create completion directory: %w", err)
		}
		installPath = filepath.Join(completionDir, binName)
		if err := os.WriteFile(installPath, []byte(scriptContent.String()), 0644); err != nil {
			return fmt.Errorf("failed to write completion script: %w", err)
		}

		bashrcPath := filepath.Join(homeDir, ".bashrc")
		sourceLine := fmt.Sprintf("source %s", installPath)
		if err := addSourceLineIfMissing(bashrcPath, sourceLine, sourceLine); err != nil {
			fmt.Fprintf(os.Stderr, "warning: could not update .bashrc: %v\n", err)
			fmt.Fprintf(os.Stderr, "add this line manually: %s\n", sourceLine)
		}
		fmt.Printf("bash completion installed to: %s\n", installPath)
		fmt.Println("run 'source ~/.bashrc' or restart your terminal to enable completions")

	case "zsh":
		completionDir := filepath.Join(homeDir, ".zsh", "completion")
		if err := os.MkdirAll(completionDir, 0755); err != nil {
			return fmt.Errorf("failed to create completion directory: %w", err)
		}
		installPath = filepath.Join(completionDir, "_"+binName)
		if err := os.WriteFile(installPath, []byte(scriptContent.String()), 0644); err != nil {
			return fmt.Errorf("failed to write completion script: %w", err)
		}

		zshrcPath := filepath.Join(homeDir, ".zshrc")
		fpathLine := "fpath=(~/.zsh/completion $fpath)"
		compinitLine := "autoload -Uz compinit && compinit"
		if err := addSourceLineIfMissing(zshrcPath, fpathLine, "~/.zsh/completion"); err != nil {
			fmt.Fprintf(os.Stderr, "warning: could not update .zshrc: %v\n", err)
		}
		if err := addSourceLineIfMissing(zshrcPath, compinitLine, "compinit"); err != nil {
			fmt.Fprintf(os.Stderr, "warning: could not update .zshrc: %v\n", err)
		}
		fmt.Printf("zsh completion installed to: %s\n", installPath)
		fmt.Println("run 'source ~/.zshrc' or restart your terminal to enable completions")

	default:
		return fmt.Errorf("unsupported shell: %s", shell)
	}

	return nil
}

// addSourceLineIfMissing prepends line to the file at rcPath unless checkStr
// is already found anywhere in the file's content. Creates the file if absent.
func addSourceLineIfMissing(rcPath, line, checkStr string) error {
	content, err := os.ReadFile(rcPath)
	if err != nil {
		if os.IsNotExist(err) {
			return os.WriteFile(rcPath, []byte(line+"\n"), 0644)
		}
		return err
	}
	if strings.Contains(string(content), checkStr) {
		return nil
	}
	return os.WriteFile(rcPath, []byte(line+"\n"+string(content)), 0644)
}

// uninstallCompletion removes the completion script file and cleans up rc files.
func uninstallCompletion(shell, binName string) error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	switch shell {
	case "bash":
		completionPath := filepath.Join(homeDir, ".bash_completion.d", binName)
		if err := os.Remove(completionPath); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("failed to remove completion script: %w", err)
		}
		bashrcPath := filepath.Join(homeDir, ".bashrc")
		if err := removeSourceLine(bashrcPath, completionPath); err != nil {
			fmt.Fprintf(os.Stderr, "warning: could not update .bashrc: %v\n", err)
		}
		fmt.Printf("bash completion uninstalled from: %s\n", completionPath)

	case "zsh":
		completionPath := filepath.Join(homeDir, ".zsh", "completion", "_"+binName)
		if err := os.Remove(completionPath); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("failed to remove completion script: %w", err)
		}
		fmt.Printf("zsh completion uninstalled from: %s\n", completionPath)
		fmt.Println("note: fpath/compinit lines remain in .zshrc for other completions")

	default:
		return fmt.Errorf("unsupported shell: %s", shell)
	}

	return nil
}

// removeSourceLine removes every line containing checkStr from rcPath.
func removeSourceLine(rcPath, checkStr string) error {
	content, err := os.ReadFile(rcPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	lines := strings.Split(string(content), "\n")
	filtered := lines[:0]
	for _, l := range lines {
		if !strings.Contains(l, checkStr) {
			filtered = append(filtered, l)
		}
	}

	if len(filtered) == len(lines) {
		return nil // nothing removed
	}
	return os.WriteFile(rcPath, []byte(strings.Join(filtered, "\n")), 0644)
}
